{{- $name := include "svai.name" . -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    {{- include "svai.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "svai.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "svai.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "svai.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }} {{"# {\"$imagepolicy\":\""}}{{ $name }}-imagepolicy-{{ .Values.env }}"}
          env:
          {{- range .Values.environment.variables }}
            name: {{ .name }}
            value: {{ .value }}
          {{- end }}
          {{- range .Values.environment.secrets }}
            name: {{ .nameOfEnvVar }}
            value: {{ .nameInKeyVault }}@azurekeyvault
          {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          startupProbe:
            httpGet:
              path: /startup
              port: 80
              scheme: http
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 15
            successThreshold: 1
            failureThreshold: 4
          readinessProbe:
            httpGet:
              path: /ready
              port: 80
              scheme: http
            initialDelaySeconds: 3
            periodSeconds: 30
            timeoutSeconds: 20
            successThreshold: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
