{{- if .Values.ingress.enabled -}}
{{- $fullName := include "svai.fullname" . -}}
{{- $dnsName := .Values.dnsName -}}

{{- $svcPort := .Values.service.port -}}
{{- $url := print $dnsName ".security.svai.dev" -}}

{{- if .Values.prod }}
{{- $url = print $dnsName ".security.svai.io" -}}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "svai.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }} 
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
      - {{ $url | quote }}
      secretName: {{ $secretName := print $fullName "-tls-certificate" }}{{ $secretName }}
  rules:
    - host: {{ $url | quote }}
      http:
        paths:
          {{- range .Values.ingress.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
{{- end }}
