{{- $name := include "svai.name" . -}}
{{- $dns := include "svai.dns" . -}}

{{- range .Values.environment.secrets }}
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: {{ .nameInKeyVault }}
spec:
  vault:
    name: {{ .vault }}
    object:
      type: secret
      name: {{ .nameInKeyVault }}
---
{{- end }}
{{- if .Values.ingress.acmebot }}
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: {{ $name }}-tls-certificate-certificate-sync
spec:
  vault:
  {{- if eq (lower .Values.env ) "prod"}}
    name: common-infra-kv-prod
  {{- else }}
    name: common-infra-kv-dev
  {{- end }}  
    object:
      type: certificate
      name: {{ $dns | replace "." "-" }}
  output:
    secret:
      name: {{ $name | replace "." "-" }}-tls-certificate
      type: kubernetes.io/tls
      chainOrder: ensureserverfirst
{{- end }}


# (Legge til støtte for k8s secrets)