name: 'Build'
description: 'Build helm chart'
inputs:
  helm-publish-repository:  
    description: 'Helm repository to publish to'
    required: false
    default: 'sparebankenvest/helm-charts'
  helm-publish-branch:  
    description: 'Helm branch to publish to'
    required: false
    default: 'gh-pages'
  helm-verify-repo:  
    description: 'Helm repo to verify against'
    required: false
    default: 'https://charts.spvapi.no'
  
runs:
  using: "composite"
  steps: 
    - name: Commit files
      shell: bash  
      run: |
        cd publish
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add .
        git commit -m "Published by GitHubActions"

    - name: Configure git key
      shell: bash  
      run: |
        SSH_DIR="${HOME}/.ssh"
        mkdir "${SSH_DIR}"
        ssh-keyscan -t rsa github.com > "${SSH_DIR}/known_hosts"
        echo "${{ secrets.GH_PAGES_TOKEN }}" > "${SSH_DIR}/id_rsa"
        chmod 400 "${SSH_DIR}/id_rsa"

    - name: Push Helm charts
      shell: bash  
      run: |
        cd publish

        git remote rm origin || true
        git remote add origin "git@github.com:${{ inputs.helm-publish-repository }}.git"
        git push origin "${{ inputs.helm-publish-branch }}"

    # - name: Verify
    #   shell: bash  
    #   run: |
    #     helm repo add spv-charts ${{ inputs.helm-verify-repo }}
    #     helm repo update
    #     helm repo list
    #     helm show chart spv-charts/azure-key-vault-controller --version 0.1.0-alpha.2
