{{- range .Values.secretsEnc }}
{{- $name := include "common.name" $ -}}
{{- if .data }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $name }}-{{ .name }}
  namespace: {{ $.Release.Namespace }}
  creationTimestamp: null
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    {{ .fileName }}: {{ .data }}
{{- end }}
{{- end }}
