{{- range .Values.secrets }}
{{- $name := include "common.name" $ -}}
{{- if .data }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-{{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
stringData:
  {{ .fileName }}: |
    {{- .data | trim | nindent 4 }}
type: Opaque
{{- end }}
{{- end }}
