{{- if and .Values.mangedIdentities.enabled .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "mic.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mic.labels" . | nindent 4 }}
    app.kubernetes.io/component: mic

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "akv2k8s.mic.fullname" . }}
  labels:
    {{- include "mic.labels" . | nindent 4 }}
    app.kubernetes.io/component: mic
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: [ "list", "watch" ]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "create", "update"]
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: [ "create", "get", "update"]
- apiGroups: ["aadpodidentity.k8s.io"]
  resources: ["azureidentitybindings", "azureidentities"]
  verbs: ["get", "list", "watch", "post", "update"]
- apiGroups: ["aadpodidentity.k8s.io"]
  resources: ["azurepodidentityexceptions"]
  verbs: ["list", "update"]
- apiGroups: ["aadpodidentity.k8s.io"]
  resources: ["azureassignedidentities"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "akv2k8s.mic.fullname" . }}
  labels:
    {{- include "mic.labels" . | nindent 4 }}
    app.kubernetes.io/component: mic
subjects:
- kind: ServiceAccount
  name: {{ template "akv2k8s.mic.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "akv2k8s.mic.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}