{{- if and .Values.controller.enabled .Values.controller.metrics.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "akv2k8s.controller.fullname" . }}
  labels:
    {{- include "akv2k8s.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.controller.metrics.externalPort }}
      targetPort: {{ .Values.controller.metrics.internalPort }}
      protocol: TCP
  selector:
    {{- include "akv2k8s.selectors" . | nindent 4 }}
    {{- include "akv2k8s.components.controller" . | nindent 4 }}
{{- end }}
