{{- if .Values.ingress.enabled -}}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "zeebe-operate.fullname" . }}
  labels: {{ include "zeebe-operate.labels" . | nindent 4 }}
{{- with .Values.ingress.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
{{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
              service:
                name: {{ include "zeebe-operate.fullname" . }}
                port:
                  number: 80
              {{- else }}
              serviceName: {{ include "zeebe-operate.fullname" . }}
              servicePort: 80
              {{- end }}
{{- end }}
